spring:
  profiles:
    active: dev

  # java mail
  mail:
    host: smtp.163.com
    username: xx#@163.com
    password: xxxxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth=true:
          starttls:
            enable: false
            required: false