server:
  port: 9002
logging:
  level:
    com.ervin: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启根据服务名称自动转发
          lower-case-service-id: true #微服务名称已小写形式呈现
      routes:
        - id: serviceproducer # 路由标示，必须唯一
          uri: lb://producer-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/echo/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: serviceconsumer # 路由标示，必须唯一
            uri: lb://consumer-service # 路由的目标地址
            predicates: # 路由断言，判断请求是否符合规则
              - Path=/main/** # 路径断言，判断路径是否是以/user开头，如果是则符合