feign:
  httpclient:
    enabled: true # ??HttpClient???
    max-connections: 200 # ?????
    max-connections-per-route: 50 # ??????????
  client:
    config:
      service-producer:  #?????????
        loggerLevel: FULL
  #???hystrix???
  hystrix:
    enabled: true
